{
 "title": "Disha Dashboard",
 "description": "Disha Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(http_request_duration_seconds_bucket{le=\"1.5\",status_code=~\"^2..$\"})+  (sum(http_request_duration_seconds_bucket{le=\"10\",status_code=~\"^2..$\"})/2)) / sum(http_request_duration_seconds_bucket)"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum (http_request_duration_seconds_count{status_code=~\"^5..$\"}) OR on () vector(0)) +  (sum (http_request_duration_seconds_count{status_code=~\"^4..$\"}) OR on () vector(0))/ sum (http_request_duration_seconds_count)) * 100"
    }
   ]
  },
  {
   "title": "GraphQL Requests In 24H",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(graphql_resolver_time_count[6s])- min_over_time(graphql_resolver_time_count[24h]))"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rate(pm2_cpu[1m]))" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(pm2_memory)) / (sum(machine_memory_bytes))"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^5..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^3..$\"}[1m]))",
     "legendFormat": "3XX Success Rate"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (rate(http_request_duration_seconds_sum[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 1.5ms, tolerated: 10ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(http_request_duration_seconds_bucket{le=\"1.5\",status_code=~\"^2..$\"}[1m]))\n+\n  (sum(irate(http_request_duration_seconds_bucket{le=\"10\",status_code=~\"^2..$\"}[1m]))/2)\n) / sum(irate(http_request_duration_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"+inf\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 1ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.003\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 3ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.03\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 30ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.1\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.3\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 300ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"1.5\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 1500ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"10\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 10000ms (%)"
    }
   ]
  },
  {
   "title": "Top 10 API calls (by path) In Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,max_over_time(http_request_duration_seconds_count[6s])- min_over_time(http_request_duration_seconds_count[24h]))"
    }
   ]
  },
  {
   "title": "Top 10 API Error Calls ( 5XX and 4XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,max_over_time(http_request_duration_seconds_count{code=~\"^5..$\"}[6s])- min_over_time(http_request_duration_seconds_count{code=~\"^5..$\"}[24h]))"
    },
    {
     "expr": "topk(10,max_over_time(http_request_duration_seconds_count{status_code=~\"^[4,5]..$\"}[6s])- min_over_time(http_request_duration_seconds_count{status_code=~\"^[4,5]..$\"}[24h]))"
    }
   ]
  }
 ]
}